apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: mock-secret-demo-
spec:
  owner: dev
  displayName: mock-secret-demo
  cluster: cluster-1
  pipeline: fournos-run-only
  executionEngine: forge
  executionEngineSpec:
    resolveImage: forge-core:main
    project: secret-demo
    args:
      - demo
