apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: test-job-
spec:
  owner: perf-team
  displayName: sample-benchmark
  cluster: cluster-1
  forge:
    project: llm-d
    args:
      - cks
      - something-else
    configOverrides:
      vllm:
        version: 0.15.1
      logging:
        enabled: true
        level: debug
  env:
    OCPCI_SUITE: regression
    OCPCI_VARIANT: nightly
