apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ocpci-fournos-job-manager
  namespace: psap-automation
subjects:
  - kind: ServiceAccount
    name: ocpci
    namespace: fournos-controller
roleRef:
  kind: Role
  name: ocpci-fournos-job-manager
  apiGroup: rbac.authorization.k8s.io
