apiVersion: apps/v1
kind: Deployment
metadata:
  name: fournos
  labels:
    app: fournos
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fournos
  template:
    metadata:
      labels:
        app: fournos
    spec:
      serviceAccountName: fournos
      containers:
        - name: fournos
          image: quay.io/rh_perfscale/fournos:latest
          env:
            - name: FOURNOS_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 8080
              name: health
          livenessProbe:
            httpGet:
              path: /healthz
              port: health
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
          resources:
            requests:
              cpu: 500m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 512Mi
