apiVersion: shipwright.io/v1beta1
kind: Build
metadata:
  name: forge-main-build
  labels:
    app: forge
    component: image-build
  annotations:
    description: "Build FORGE core image from main branch"
spec:
  source:
    type: Git
    git:
      url: https://github.com/openshift-psap/forge
      revision: main
  strategy:
    name: buildah
    kind: ClusterBuildStrategy
  paramValues:
  - name: dockerfile
    value: projects/core/image/Containerfile
  output:
    # the namespace is hardcoded here, but I don't know how to make that dynamic -,-
    image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/forge-core:main

  timeout: 30m
  resources:
    limits:
      cpu: "2"
      memory: 4Gi
    requests:
      cpu: 500m
      memory: 1Gi
