# Single-step pipeline: validate only (used for smoke testing the connectivity to the target clusters).
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: fournos-validate-only
  annotations:
    fournos.dev/resolve-image: image-registry.openshift-image-registry.svc:5000/${NAMESPACE}/forge-core:main
spec:
  params:
    - name: fjob-name
      type: string
    - name: fournos-namespace
      type: string
    - name: kubeconfig-secret
      type: string
  tasks:
    - name: validate
      taskRef:
        name: fournos-validate
      params:
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
