# Full three-step pipeline: pre_cleanup -> prepare → test → post-cleanup.
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: forge-full
spec:
  params:
    - name: fjob-name
      type: string
    - name: fournos-namespace
      type: string
    - name: kubeconfig-secret
      type: string

  tasks:
    - name: pre-cleanup
      taskRef:
        name: forge-step
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-namespace
          value: "$(params.fournos-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: pre-cleanup

    - name: prepare
      taskRef:
        name: forge-step
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-namespace
          value: "$(params.fournos-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: prepare

    - name: test
      runAfter: [prepare]
      taskRef:
        name: forge-step
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-namespace
          value: "$(params.fournos-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: test

  finally:
    - name: post-cleanup
      taskRef:
        name: forge-step
      params:
        - name: fjob-name
          value: "$(params.fjob-name)"
        - name: fournos-namespace
          value: "$(params.fournos-namespace)"
        - name: kubeconfig-secret
          value: "$(params.kubeconfig-secret)"
        - name: job-step
          value: pre-cleanup # there's currently no post-cleanup step
