apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: forge-step
spec:
  params:
    - name: forge-project
      type: string
    - name: forge-preset
      type: string
    - name: forge-config-overrides
      type: string
    - name: env
      type: string
    - name: kubeconfig-secret
      type: string
    - name: gpu-count
      type: string
    - name: job-name
      type: string
    - name: job-step
      type: string
    - name: secrets
      type: array
  steps:
    - name: forge
      image: image-registry.openshift-image-registry.svc:5000/psap-automation/forge-core:main
      env:
      - name: KUBECONFIG
        value: /workspace/kubeconfig/kubeconfig
      - name: FORGE_CONFIG_OVERRIDES
        value: "$(params.forge-config-overrides)"
      - name: FOURNOS_ENV
        value: "$(params.env)"
      - name: FOURNOS_STEP
        value: "$(params.job-step)"
      volumeMounts:
        - name: kubeconfig
          mountPath: /workspace/kubeconfig
          readOnly: true
      script: |
        #!/usr/bin/env bash

        set -euo pipefail
        set -x

        cat > fournos_config.yaml <<EOF
        preset: "$(params.forge-preset)"
        gpu-count "$(params.gpu-count)"
        job-name: "$(params.job-name)"
        EOF
        echo "--- FOURNOS configuration:"
        cat fournos_config.yaml
        echo "---"

        # will be changed to /app/forge when the rename PR is merged
        exec /app/topsail/bin/run_ci "$(params.forge-project)" ci "$FOURNOS_STEP"

  volumes:
    - name: kubeconfig
      secret:
        secretName: $(params.kubeconfig-secret)
