apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: forge-step
spec:
  params:
    - name: fjob-name
      type: string
    - name: fournos-namespace
      type: string
    - name: kubeconfig-secret
      type: string
    - name: job-step
      type: string
  steps:
    - name: forge
      image: image-registry.openshift-image-registry.svc:5000/$(context.taskRun.namespace)/forge-core:main
      imagePullPolicy: Always
      env:
      - name: TARGET_KUBECONFIG
        value: /var/run/secrets/fournos-kubeconfig/kubeconfig
      - name: FJOB_NAME
        value: "$(params.fjob-name)"
      - name: FOURNOS_NAMESPACE
        value: "$(params.fournos-namespace)"
      - name: FOURNOS_STEP
        value: "$(params.job-step)"
      - name: FOURNOS_SECRETS
        value: /var/run/secrets/fournos
      - name: FOURNOS_CI
        value: "true"
      volumeMounts:
        - name: kubeconfig
          mountPath: /var/run/secrets/fournos-kubeconfig
          readOnly: true
        - name: vault-secrets
          mountPath: /var/run/secrets/fournos
          readOnly: true
      script: |
        #!/usr/bin/env bash

        set -o pipefail
        set -o errexit
        set -o nounset
        set -o errtrace

        export ARTIFACT_DIR=/tmp/artifacts
        mkdir -p "${ARTIFACT_DIR}"

        exec &> >(tee -a "$ARTIFACT_DIR/run.log")

        # Fetch FournosJob from the hub cluster (in-cluster SA) before
        # switching KUBECONFIG to the target cluster.
        oc get "fjob/$FJOB_NAME" -n "$FOURNOS_NAMESPACE" -oyaml > $ARTIFACT_DIR/fournos_fjob.yaml

        export KUBECONFIG=$TARGET_KUBECONFIG

        PULL_BASE_SHA=$(cat "$ARTIFACT_DIR/fournos_fjob.yaml" | yq -r .spec.env.PULL_BASE_SHA)
        if [[ "$PULL_BASE_SHA" != null ]]; then
          export PULL_BASE_SHA
        else
          unset PULL_BASE_SHA
        fi

        PULL_PULL_SHA=$(cat "$ARTIFACT_DIR/fournos_fjob.yaml" | yq -r .spec.env.PULL_PULL_SHA)
        if [[ "$PULL_PULL_SHA" != null ]]; then
          export PULL_PULL_SHA
        else
          unset PULL_PULL_SHA
        fi

        if [[ "${PULL_PULL_SHA:-}" ]]; then
          echo
          echo "Updating to PULL_PULL_SHA=$PULL_PULL_SHA ..."

          git -C "$FORGE_HOME" fetch --quiet origin "$PULL_PULL_SHA"
          git -C "$FORGE_HOME" reset --hard FETCH_HEAD
        else
          echo "No PULL_PULL_SHA, using the image commit"
        fi
        git show --quiet

        FORGE_PROJECT=$(cat "$ARTIFACT_DIR/fournos_fjob.yaml" | yq -r .spec.forge.project)
        if [[ -z "$FORGE_PROJECT" || "$FORGE_PROJECT" == null ]]; then
          echo "ERROR: invalid .spec.forge.project='$FORGE_PROJECT' in $FOURNOS_NAMESPACE/$FJOB_NAME"
          exit 1
        fi

        exec bin/run_ci "$FORGE_PROJECT" ci "$FOURNOS_STEP"

  volumes:
    - name: kubeconfig
      secret:
        secretName: $(params.kubeconfig-secret)
