apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: test-connectivity-job-
spec:
  owner: perf-team
  displayName: test-connectivity-job
  pipeline: fournos-validate-only
  cluster: cluster-1
  hardware:
    gpuType: a100
    gpuCount: 1
  executionEngine: forge
  executionEngineSpec:
    resolveImage: forge-core:main
    project: none
    args: []
