apiVersion: fournos.dev/v1
kind: FournosJob
metadata:
  generateName: forge-full-sample-
spec:
  owner: perf-team
  displayName: forge-full-sample
  cluster: athena-fire
  pipeline: forge-full
  forge:
    project: llm_d
    args:
      - cks
  env:
    OCPCI_SUITE: regression
    OCPCI_VARIANT: nightly
