apiVersion: v1
kind: ServiceAccount
metadata:
  name: fournos-cluster
  namespace: psap-automation
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fournos-cluster
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: fournos-cluster
subjects:
  - kind: ServiceAccount
    name: fournos-cluster
    namespace: psap-automation
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fournos-cluster
  namespace: psap-automation
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fournos-cluster
  template:
    metadata:
      labels:
        app: fournos-cluster
    spec:
      serviceAccountName: fournos-cluster
      containers:
        - name: fournos-cluster
          image: quay.io/memehta/fournos-cluster:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
              name: healthz
              protocol: TCP
          env:
            - name: FOURNOS_CLUSTER_NAMESPACE
              value: psap-automation
            - name: FOURNOS_CLUSTER_SECRETS_NAMESPACE
              value: psap-secrets
          resources:
            requests:
              cpu: 50m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 256Mi
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL
            runAsNonRoot: true
            seccompProfile:
              type: RuntimeDefault
